version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    #volumes: 
    #  - ./mongo:/etc/mongo:rw
    restart: always
   # environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    #command: "--config /etc/mongo/mongod.conf"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    depends_on: 
      - mongo