version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    #volumes: 
    #  - ./mongo:/etc/mongo:rw
    restart: always
   # environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    #command: "--config /etc/mongo/mongod.conf"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    depends_on: 
      - mongo
    #environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example

  application:
    image: node:slim
    container_name: UniNote
    restart: always
    user: node
    working_dir: /home/node/app
    volumes: 
      - ./:/home/node/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: docker
    command: "./npm start"
    links:
      - mongo
    depends_on: 
      - mongo